#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2008 Rod Taylor
#               2014      Mark Wong
#               2014      2ndQuadrant, Ltd.
#

if [ -z ${PGDATA} ]; then
	echo "PGDATA not defined."
	exit 1
fi

LOGFILE="dbt3.log"
OUTDIR="."
NODES=1
while getopts "fn:o:p:" OPT; do
	case ${OPT} in
	f)
		rm -f ${PGDATA}/postmaster.pid
		;;
	n)
		NODES=$OPTARG
		;;
	o)
		OUTDIR=${OPTARG}
		;;
	p)
		PARAMETERS="${OPTARG}"
		;;
	\?)
		exit 1
		;;
	esac
done

gtm_ctl -D $PGDATA/g -Z gtm -l $OUTDIR/gtm.log start
i=1
while [ $i -le $NODES ]; do
	PORT=$(( $BASEPORT + $i ))
	POOLPORT=$(( $BASEPOOLPORT + $i ))
	pg_ctl -Z datanode -w -D $PGDATA/d$i -l $OUTDIR/datanode-$i.log \
			-o "-p $PORT -c pooler_port=$POOLPORT $PARAMETERS" start
	i=$(( $i + 1 ))
done
pg_ctl -Z coordinator -w -D $PGDATA/c -l $OUTDIR/coordinator.log \
		-o "-c pooler_port=$BASEPOOLPORT $PARAMTERS" start
