#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2008 Rod Taylor
#               2014      Mark Wong
#               2014      2ndQuadrant, Ltd.

if [ -z ${PGDATA} ]; then
	echo "PGDATA not defined."
	exit 1
fi

while getopts "n:" OPT; do
	case ${OPT} in
	n)
		NODES=$OPTARG
		;;
	esac
done

pg_ctl -Z coordinator -w -D $PGDATA/c stop -m fast
i=1
while [ $i -le $NODES ]; do
	PORT=$(( $BASEPORT + $i ))
	POOLPORT=$(( $BASEPOOLPORT + $i ))
	pg_ctl -Z datanode -w -D $PGDATA/d$i stop -m fast
	i=$(( $i + 1 ))
done
gtm_ctl -D $PGDATA/g -Z gtm stop -m fast
