#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.

# dont start script as root!
id=`id | sed s/\(.*// | sed s/uid=//`

if [ "$id" = "0" ]; then
	echo "dont start script as root"
	exit 1
fi

if [ -z ${PGDATA} ]; then
    echo "PGDATA not defined."
    exit 1
fi

if [ -z ${PGDATABASE} ]; then
    echo "PGDATABASE environment variable not defined"
    exit 1
fi

PSQL="psql -X -d postgres"

XLOGPATH=""
OUTPUT_DIR="."
NODES=1
while getopts "n:o:p:x:" OPT; do
	case ${OPT} in
	n)
		NODES=$OPTARG
		;;
	o)
		OUTPUT_DIR=${OPTARG}
		;;
	p)
		PARAMOPT="-p \"$OPTARG\""
		;;
	x)
		XLOGPATH=${OPTARG}
		;;
	\?)
		exit 1
		;;
	esac
done

dbt3-pgsql-stop-db -n $NODES

# Create database
SKIP=0
echo "Creating database..."
if [ -d ${PGDATA} ]; then
	echo "PGData directory '${PGDATA}' already exists, skipping initdb..."
	SKIP=1
else
	# initialize database cluster
	echo "initializing database cluster..."

	initdb -D $PGDATA/c --nodename coordinator
	i=1
	while [ $i -le $NODES ]; do
		initdb -D $PGDATA/d$i --nodename datanode$i
		i=$(( $i + 1 ))
	done
	initgtm -D $PGDATA/g -Z gtm
fi

eval dbt3-pgsql-start-db -n $NODES -o $OUTPUT_DIR $PARAMOPT
if [ $SKIP -eq 1 ]; then
	exit 0
fi

$PSQL -c "ALTER NODE coordinator WITH (TYPE = 'coordinator', PORT = 5432);"

i=1
while [ $i -le $NODES ]; do
	PORT=$(( $BASEPORT + $i ))
	$PSQL -c "CREATE NODE datanode$i WITH (TYPE = 'datanode', PORT = $PORT);"
	$PSQL -c "EXECUTE DIRECT ON (datanode$i) 'CREATE NODE coordinator WITH (TYPE = ''coordinator'', PORT = $PORT)';"
	i=$(( $i + 1 ))
done

i=1
while [ $i -le $NODES ]; do
	PORT=$(( $BASEPORT + $i ))
	j=1
	while [ $j -le $NODES ]; do
		PORT2=$(( $BASEPORT + $j ))
		if [ $j -eq $i ]; then
			$PSQL -c "EXECUTE DIRECT ON (datanode$j) 'ALTER NODE datanode$i WITH (TYPE = ''datanode'', PORT = $PORT)';"
		else
			$PSQL -c "EXECUTE DIRECT ON (datanode$j) 'CREATE NODE datanode$i WITH (TYPE = ''datanode'', PORT = $PORT)';"
		fi
		j=$(( $j + 1 ))
	done

	i=$(( $i + 1 ))
done

$PSQL -c "SELECT pgxc_pool_reload();"
i=1
while [ $i -le $NODES ]; do
	$PSQL -c "EXECUTE DIRECT ON (datanode$i) 'SELECT pgxc_pool_reload()';"
	i=$(( $i + 1 ))
done

createdb ${PGDATABASE} || exit 1
